export const CONSTANTS = Object.freeze({
  BASE_URL: 'https://api.spotify.com/v1',
  SPOTIFY_CLIENT_ID: 'ENTER_YOUR_SPOTIFY_CLIENT_ID',
  SPOTIFY_CLIENT_SECRET: 'ENTER_YOUR_SPOTIFY_CLIENT_SECRET',
});
